spring:
    application:
        name: gateway-service
    cloud:
        gateway:
            default-filters:
                - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            discovery:
                locator:
                    enabled: true
                    lower-case-service-id: true
            routes:
                - id: traffic-service
                  uri: lb://traffic-service
                  predicates:
                    - Path=/api/traffic/**
                  filters:
                    - RewritePath=/api/traffic/(?<Segment>.*), /$(segment)  
            httpclient:
                connect-timeout: 2000
                response-timeout: 5s         

        loadbalancer:
            ribbon:
                enabled: false
    sleuth:
        sampler:
            probability: 1.0
    zipkin:
        base-url: http://localhost:9411
        enabled: true
    data:
        redis:
            host: localhost
            port: 6379
management:
    endpoints:
        web:
            exposure:
                include: '*'
    prometheus:
        metrics:
            export:
                enabled: true
server:
    port: 8080
logging:
    level:
        root: INFO
        org.springframework.cloud.gateway: DEBUG

# Swagger aggregation (for web UIs like Swagger UI frontend)
springdoc:
    swagger-ui:
        urls:
            - name: traffic-service
              url: /api/traffic/v3/api-docs
            - name: user-service
              url: /api/users/v3/api-docs
    api-docs:
        enabled: true
    default-produces-media-type: application/json
    